### ISSUE TITLE
Compatibiltiy with latest Carla versions?

### ISSUE THREAD

**Issue by Rajat-Mehta** [Ozzyz/carla-data-export#2]
Can I use your work to generate training data using Carla 0.9.8 version? And how?

**Comment by Ozzyz** [comment]
I am not sure whether or not 0.9.8 can be supported by this library. There might be a lot of breaking changes between 0.9.X and 0.8.X, so my advice would be to look deeper into what these changes are. I am currently not working with Carla, so unfortunately I can't help you with questions regarding new versions.

**Comment by husamhamu** [comment]
Hi @Rajat-Mehta , I wonder if you tried to generate data using CARLA 0.9.8 ?

**Comment by AOOOOOA** [comment]
> Can I use your work to generate training data using Carla 0.9.8 version? And how?

Hi, @Rajat-Mehta , I also work on a project which needs to generate KITTI-format Carla data. I met you several times under several Carla-KITTI-repos. However, most of them use the Carla-0.8.x, which has a different API from 0.9.x.

May I ask have you found a suitable method to generate KITTI data using Carla-0.9.x?

Thanks!

**Comment by amsvenkat** [comment]
Hi @Rajat-Mehta  @husamhamu  @AOOOOOA  - Were you able to get a solution for the Carla 0.9.x ? please could you let me know.  By converting x,y,z to y,-z,x and taking relative rotation of camera and the actor, my bounding boxes arent coming in correctly, when recreated. Have you faced this ?

**Comment by Ozzyz** [comment]
@amsvenkat without looking at your code it is difficult to say, but make sure that you rotate and translate in the correct order. If you first translate, then rotate you will get different results
