### ISSUE TITLE
How can I add another RGB camera?

### ISSUE THREAD

**Issue by trung6** [Ozzyz/carla-data-export#3]
Hi, thanks for your code. I just wonder if I can add another camera like the setting in Kitti dataset with left/right cameras? Thanks.

**Comment by Ozzyz** [comment]
Hey!
To add more cameras you can modify `settings.py`. This file has code to add both cameras and LIDAR.
For instance, the main camera is set up as follows:
```
    camera0 = sensor.Camera('CameraRGB')
    camera0.set_image_size(WINDOW_WIDTH, WINDOW_HEIGHT)
    camera0.set_position(0, 0.0, CAMERA_HEIGHT_POS)
    camera0.set_rotation(0.0, 0.0, 0.0)
    settings.add_sensor(camera0)
``` 
Please note that you might require further modifications in other files, for instance if you want to project stuff onto these camera views.
Happy coding! :)

**Comment by trung6** [comment]
Got it. Thanks a lot!
