### ISSUE TITLE
Data set classification

### ISSUE THREAD

**Issue by liulingfeng123** [Ozzyz/carla-data-export#4]
Hello, why can only generate a data set of cars, how to generate cyclists and pedestrians

**Comment by Ozzyz** [comment]
Hey! To select the classes you want to generate data for, please change the config in `constants.py` :) 
https://github.com/Ozzyz/carla-data-export/blob/a656510d2e25a9d44ea36c506ca5c517cb6c583d/constants.py#L6

**Comment by liulingfeng123** [comment]
Thank you for your reply, I have modified CLASSES_TO_LABEL = ["Vehicle", "Pedestrian"] this, this can run successfully, but I modified the code to CLASSES_TO_LABEL = ["Vehicle", "Pedestrian", "Cyclist"]. Will report an error

**Comment by liulingfeng123** [comment]
the error is ValueError: Protocol message Agent has no field cyclist.

**Comment by Ozzyz** [comment]
Okay. This is the method that detects the types of classes. I do not recall if Carla supports cyclists directly as a class. You can check if it is under one of the categories, either pedestrian or vehicle. Then you probably can do some calculations and width and height to determine whether the agent is a cyclist. 
https://github.com/Ozzyz/carla-data-export/blob/a656510d2e25a9d44ea36c506ca5c517cb6c583d/datageneration.py#L452-L455

Hope this helps :)  Apologies for being a bit vague. but I have not been working on this in a long time

**Comment by liulingfeng123** [comment]
Thanks for your reply, I will try it. Hope you have a good time.

**Comment by liulingfeng123** [comment]
Thank you for your reply, I will try it out, hope you have a happy life every day

**Comment by liulingfeng123** [comment]
Thank you for your reply, I will try it out, hope you have a happy life every day

**Comment by Ozzyz** [comment]
@liulingfeng123 no problem! Happy coding : ) And thanks for the uplifting message. Wish you the best!

**Comment by atusi-nakajima** [comment]
Has this been resolved?
If you figured out how to classify other classes as well, please let me know.
