### ISSUE TITLE
Question about Calib

### ISSUE THREAD

**Issue by Jungtaxi** [Ozzyz/carla-data-export#8]
Hello.

I was able to convert Carla Data to Kitti format Data by your github code.
Thank you very much.

It's Really nice code that I could easily apply.

But There's a Question about Calib, tr_velodyne_to_cam.

`    TR_velodyne = np.array([[0, -1, 0],
                            [0, 0, -1],
                            [1, 0, 0]])`

Since the projection matrix contains a rotation matrix, I thought that's why the following matrix expression was created to preserve the value of P matrix. but why is it this form instead f a Identity matrix?

Please correct me if I am mistaken.

Thank you so much

**Comment by Ozzyz** [comment]
Hey @Jungtaxi ! 
I think this was because there were differences between the coordinate systems of the velodyne and camera, but I must admit that this is a bit unclear because haven't looked at the code in 4 years. 
So this matrix will convert a point (x,y,z) into (-y,-z,x).

**Comment by Jungtaxi** [comment]
Thanks! Its really helped.

**Comment by Ozzyz** [comment]
Awesome! 

However, I should note that this code is not suited for the latest version of Carla, and we do not plan on supporting it.. If you need a newer version of Carla, see for instance https://github.com/Ozzyz/carla-data-export/issues/7#issuecomment-1207414022
